repos:
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    # Ruff version.
    rev: v0.0.276
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: 'https://github.com/myint/autoflake'
    rev: master
    hooks:
      - id: autoflake
        args:
          - '--in-place'
          - '--remove-duplicate-keys'
          - '--remove-unused-variables'
          - '--remove-all-unused-imports'
          - '--expand-star-imports'
          - '--exclude=__init__.py'
  - repo: 'https://github.com/ambv/black'
    rev: 23.3.0
    hooks:
      - id: black
#  - repo: local
#    hooks:
#      - id: unit-test
#        name: unit-test
#        language: system
#        entry: pytest tests/
#        stages: [ commit ]
#        types: [ python ]
#        always_run: true
#        require_serial: true
#        verbose: true